function [Tt4, XCO, Qr] = fuelEquilibrium(Tt3, pt3, phi)
%FUELEQUILIBRIUM  Lookup-based fuel equilibrium helper for burner.m
%
%   [Tt4, XCO, Qr] = fuelEquilibrium(Tt3, pt3, phi)
%
%   Uses a precomputed table from Cantera (dieselEquilTable.mat) to
%   return the burner exit total temperature Tt4 [K], CO mole fraction
%   XCO [-], and heating value Qr [J/kg fuel] for the specified
%   inlet total state (Tt3, pt3) and equivalence ratio phi.
%
%   The .mat file is generated by buildDieselEquilTable.py, which uses
%   the Lecture 16 Cantera codes (dieselEquilibrium.py, etc.) to sweep
%   over phi and record Tt4, XCO, Qr.
%
%   NOTE: This version assumes Tt3 and pt3 are close to the reference
%   values used to generate the table. If they differ a lot, you should
%   regenerate the table or extend it to multiple Tt3/pt3 values.

persistent phi_vals Tt4_tab XCO_tab Qr_tab Tt3_ref pt3_ref dataLoaded

if isempty(dataLoaded)
    % Load the table created by buildDieselEquilTable.py
    S = load('dieselEquilTable.mat');
    phi_vals = S.phi_vals(:).';   % row vector
    Tt4_tab  = S.Tt4_tab(:).';
    XCO_tab  = S.XCO_tab(:).';
    Qr_tab   = S.Qr_tab(:).';
    Tt3_ref  = S.Tt3_ref;
    pt3_ref  = S.pt3_ref;
    
    dataLoaded = true;
end

% Optional: warn if Tt3 or pt3 differ a lot from reference
if abs(Tt3 - Tt3_ref) > 10
    warning('fuelEquilibrium: Tt3 differs from table reference by more than 10 K.');
end
if abs(pt3 - pt3_ref) / pt3_ref > 0.05
    warning('fuelEquilibrium: pt3 differs from table reference by more than 5%%.');
end

% Clamp phi to table bounds to avoid extrapolation
phi_min = phi_vals(1);
phi_max = phi_vals(end);
if phi < phi_min
    warning('fuelEquilibrium: phi below table range, clamping to %.3f', phi_min);
    phi = phi_min;
elseif phi > phi_max
    warning('fuelEquilibrium: phi above table range, clamping to %.3f', phi_max);
    phi = phi_max;
end

% 1D interpolation in phi
Tt4 = interp1(phi_vals, Tt4_tab, phi, 'linear');
XCO = interp1(phi_vals, XCO_tab, phi, 'linear');
Qr  = interp1(phi_vals, Qr_tab,  phi, 'linear');

end